version: "3.9"

services:
  app:
    build: .
    container_name: opspulse_app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: opspulse_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"